In [105]:
''' 
Shuya Chiang 03/08/2019
I have not given or received any unauthorized assistance on this assignment.
'''
import numpy as np

In [106]:
arry_a=np.arange(100)
arry_b=np.arange(0,100,10)
arry_c=np.linspace(0.,10., num=100)
arry_d=np.arange(100).reshape(10,10)
arry_a.shape=(10,10)
#print(arry_a,arry_b,arry_c,arry_d)
arry_a[4,5]#find the value by the index of the row =4 and the index of the column = 5 

45

In [107]:
arry_a[4] #the values of index of the row =4

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [108]:
arry_d.sum()

4950

In [109]:
arry_a.max()

99

In [110]:
arry_b.transpose()

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [111]:
arry_a+arry_d

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [112]:
arry_a*arry_d

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481],
       [3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761],
       [4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241],
       [6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921],
       [8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]])

In [113]:
np.dot(arry_a,arry_d)

array([[ 2850,  2895,  2940,  2985,  3030,  3075,  3120,  3165,  3210,
         3255],
       [ 7350,  7495,  7640,  7785,  7930,  8075,  8220,  8365,  8510,
         8655],
       [11850, 12095, 12340, 12585, 12830, 13075, 13320, 13565, 13810,
        14055],
       [16350, 16695, 17040, 17385, 17730, 18075, 18420, 18765, 19110,
        19455],
       [20850, 21295, 21740, 22185, 22630, 23075, 23520, 23965, 24410,
        24855],
       [25350, 25895, 26440, 26985, 27530, 28075, 28620, 29165, 29710,
        30255],
       [29850, 30495, 31140, 31785, 32430, 33075, 33720, 34365, 35010,
        35655],
       [34350, 35095, 35840, 36585, 37330, 38075, 38820, 39565, 40310,
        41055],
       [38850, 39695, 40540, 41385, 42230, 43075, 43920, 44765, 45610,
        46455],
       [43350, 44295, 45240, 46185, 47130, 48075, 49020, 49965, 50910,
        51855]])