In [97]:
import numpy as np
import pylab as pl
import pandas as pd
from os import chdir
from sklearn.cluster import KMeans 
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn import decomposition

In [98]:
chdir('C:/Users/Shuya C/Desktop/depaul/DSC478/hw')

In [99]:
data = pd.read_csv('segmentation_data.txt',sep=',', header=None)
print(data.shape)
data.head()

(2100, 19)


0      1   2    3    4         5         6         7         8   \
0  110.0  189.0   9  0.0  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.0  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.0  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.0  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.0  0.0  1.166667  0.691215  1.166667  1.005540   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654

In [100]:
class_lab=pd.read_csv('segmentation_classes.txt',sep='\t', header=None)
print(class_lab.shape)
class_lab.head()

(2100, 2)


0  1
0  GRASS  0
1  GRASS  0
2  GRASS  0
3  GRASS  0
4  GRASS  0

In [101]:
print(class_lab.isnull().sum())
print(data.isnull().sum())

0    0
1    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
dtype: int64


In [102]:
np.set_printoptions(precision=4,suppress=True)
#floating point numbers using fixed point notation

In [103]:
seg_data=data.values

In [104]:
#perform min-max normalization on the data matrix
scaler = MinMaxScaler()
print(scaler.fit(seg_data))
print(scaler.data_max_)

MinMaxScaler(copy=True, feature_range=(0, 1))
[ 254.      251.        9.        0.3333    0.2222   29.2222  991.7184
   44.7222 1386.3292  143.4444  137.1111  150.8889  142.5556    9.8889
   82.       24.6667  150.8889    1.        2.9125]


In [105]:
normalize_data=scaler.transform(seg_data)
print(normalize_data)
print(normalize_data.shape)

[[0.4308 0.7417 0.     ... 0.1237 0.5081 0.8318]
 [0.336  0.7333 0.     ... 0.1274 0.4633 0.837 ]
 [0.8854 0.9708 0.     ... 0.1134 0.4801 0.8448]
 ...
 [0.502  0.625  0.     ... 0.0722 0.5409 0.1759]
 [0.5889 0.6125 0.     ... 0.081  0.5031 0.1848]
 [0.4862 0.6292 0.     ... 0.0965 0.4799 0.1704]]
(2100L, 19L)


In [106]:
label=class_lab[1].to_numpy()
label.shape

(2100L,)

In [107]:
#b.perform kmeans clustering
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization

In [108]:
kmeans.fit(normalize_data)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 392.1604890877912
start iteration
done sorting
end inner loop
Iteration 1, inertia 368.47233835056943
start iteration
done sorting
end inner loop
Iteration 2, inertia 362.08392370639035
start iteration
done sorting
end inner loop
Iteration 3, inertia 358.03508680210723
start iteration
done sorting
end inner loop
Iteration 4, inertia 355.5791495726144
start iteration
done sorting
end inner loop
Iteration 5, inertia 354.200295064054
start iteration
done sorting
end inner loop
Iteration 6, inertia 353.3444794415742
start iteration
done sorting
end inner loop
Iteration 7, inertia 352.1124751473328
start iteration
done sorting
end inner loop
Iteration 8, inertia 351.40357015950264
start iteration
done sorting
end inner loop
Iteration 9, inertia 351.3269845567526
start iteration
done sorting
end inner loop
Iteration 10, inertia 351.2839551805581
start iteration
done sorting
end inner loop
Iteration 11, i

Iteration 11, inertia 370.2953666810661
start iteration
done sorting
end inner loop
Iteration 12, inertia 370.2953666810661
center shift 0.000000e+00 within tolerance 4.150157e-06
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 407.8548852843646
start iteration
done sorting
end inner loop
Iteration 1, inertia 387.2741525978356
start iteration
done sorting
end inner loop
Iteration 2, inertia 370.0742277807806
start iteration
done sorting
end inner loop
Iteration 3, inertia 362.94503964149646
start iteration
done sorting
end inner loop
Iteration 4, inertia 356.24237426280695
start iteration
done sorting
end inner loop
Iteration 5, inertia 353.5979788009149
start iteration
done sorting
end inner loop
Iteration 6, inertia 352.0157357443078
start iteration
done sorting
end inner loop
Iteration 7, inertia 351.3950307327649
start iteration
done sorting
end inner loop
Iteration 8, inertia 351.3501358780186
start iteration
done sorting
end inner loop
Ite

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [109]:
seg_names=pd.read_csv('segmentation_names.txt',sep='\t', header=None)
print(seg_names.values.tolist())

[['REGION-CENTROID-COL'], ['REGION-CENTROID-ROW'], ['REGION-PIXEL-COUNT'], ['SHORT-LINE-DENSITY-5'], ['SHORT-LINE-DENSITY-2'], ['VEDGE-MEAN'], ['VEDGE-SD'], ['HEDGE-MEAN'], ['HEDGE-SD'], ['INTENSITY-MEAN'], ['RAWRED-MEAN'], ['RAWBLUE-MEAN'], ['RAWGREEN-MEAN'], ['EXRED-MEAN'], ['EXBLUE-MEAN'], ['EXGREEN-MEAN'], ['VALUE-MEAN'], ['SATURATION-MEAN'], ['HUE-MEAN']]


In [110]:
clusters = kmeans.predict(normalize_data)
print(clusters)
print(kmeans.labels_)
print(seg_names.values.tolist())
print(kmeans.cluster_centers_)

[3 3 3 ... 0 0 2]
[3 3 3 ... 0 0 2]
[['REGION-CENTROID-COL'], ['REGION-CENTROID-ROW'], ['REGION-PIXEL-COUNT'], ['SHORT-LINE-DENSITY-5'], ['SHORT-LINE-DENSITY-2'], ['VEDGE-MEAN'], ['VEDGE-SD'], ['HEDGE-MEAN'], ['HEDGE-SD'], ['INTENSITY-MEAN'], ['RAWRED-MEAN'], ['RAWBLUE-MEAN'], ['RAWGREEN-MEAN'], ['EXRED-MEAN'], ['EXBLUE-MEAN'], ['EXGREEN-MEAN'], ['VALUE-MEAN'], ['SATURATION-MEAN'], ['HUE-MEAN']]
[[0.7707 0.4252 0.     0.014  0.0226 0.0402 0.003  0.0231 0.0021 0.0411
  0.035  0.0583 0.0288 0.7785 0.2239 0.4865 0.0593 0.5382 0.244 ]
 [0.5351 0.1502 0.     0.0278 0.0017 0.0302 0.0005 0.0268 0.0006 0.8232
  0.7797 0.8942 0.7888 0.2707 0.6664 0.2894 0.8942 0.2118 0.1251]
 [0.2561 0.3935 0.     0.0745 0.0191 0.0773 0.0041 0.0606 0.005  0.1482
  0.1381 0.1852 0.1185 0.7169 0.344  0.3555 0.1854 0.412  0.2019]
 [0.514  0.8089 0.     0.0774 0.0051 0.0545 0.0014 0.0463 0.0014 0.1088
  0.0914 0.0924 0.1427 0.6792 0.079  0.8213 0.1349 0.4145 0.8923]
 [0.2542 0.46   0.     0.0263 0.0137 0.0373 0.002

In [111]:
from sklearn.metrics import completeness_score, homogeneity_score

In [112]:
print('completeness_score = ' + str(completeness_score(label,clusters)))
print('homogeneity_score = '+str(homogeneity_score(label,clusters)))

completeness_score = 0.6131870124853009
homogeneity_score = 0.6115021163370862


In [117]:
#c. PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
seg_pca = pca.fit_transform(normalize_data)
print(seg_pca)

[[-0.6891  0.533   0.2461 -0.1978 -0.0764]
 [-0.6669  0.5107  0.338  -0.1744 -0.0412]
 [-0.712   0.7709 -0.1558 -0.0093 -0.1666]
 ...
 [-0.5077 -0.1294 -0.0822  0.096  -0.0279]
 [-0.4791 -0.0863 -0.1587  0.1082  0.0044]
 [-0.4423 -0.1062 -0.0471  0.1502  0.0152]]


In [119]:
print(pca.explained_variance_ratio_)   # 4 components can capture 95.46% fo variancne

[0.6071 0.132  0.1012 0.0454 0.0355]


In [120]:
pca_4 = PCA(n_components=4) # using 4 components 
seg_pca4 = pca_4.fit_transform(normalize_data) #transform data into a reduce dimension
print(seg_pca4)

[[-0.6891  0.533   0.2461 -0.1978]
 [-0.6669  0.5107  0.338  -0.1744]
 [-0.712   0.7709 -0.1558 -0.0093]
 ...
 [-0.5077 -0.1294 -0.0822  0.096 ]
 [-0.4791 -0.0863 -0.1587  0.1082]
 [-0.4423 -0.1062 -0.0471  0.1502]]


In [126]:
#d
kmeans.fit(seg_pca4)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 207.64069212575143
start iteration
done sorting
end inner loop
Iteration 1, inertia 193.80839778950016
start iteration
done sorting
end inner loop
Iteration 2, inertia 189.7640705306239
start iteration
done sorting
end inner loop
Iteration 3, inertia 188.1256299057908
start iteration
done sorting
end inner loop
Iteration 4, inertia 187.45667565372108
start iteration
done sorting
end inner loop
Iteration 5, inertia 187.09279587458698
start iteration
done sorting
end inner loop
Iteration 6, inertia 186.98521692158826
start iteration
done sorting
end inner loop
Iteration 7, inertia 186.96693958796612
start iteration
done sorting
end inner loop
Iteration 8, inertia 186.95837199726367
start iteration
done sorting
end inner loop
Iteration 9, inertia 186.95746858109516
center shift 1.746767e-03 within tolerance 1.746170e-05
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, i

Iteration 15, inertia 184.19707106384126
start iteration
done sorting
end inner loop
Iteration 16, inertia 184.08032983687022
start iteration
done sorting
end inner loop
Iteration 17, inertia 184.03252943636363
start iteration
done sorting
end inner loop
Iteration 18, inertia 184.0281367777564
center shift 3.160209e-03 within tolerance 1.746170e-05


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [127]:
c_pca = kmeans.predict(seg_pca4)
print(c_pca)
print(kmeans.labels_)
print(kmeans.cluster_centers_)

[5 5 5 ... 0 0 4]
[5 5 5 ... 0 0 4]
[[-0.5066 -0.0964 -0.3625 -0.085 ]
 [ 1.4145  0.0872  0.0368 -0.1732]
 [ 0.4352 -0.1055  0.1658  0.2298]
 [-0.6051 -0.3347  0.1355 -0.111 ]
 [-0.1889 -0.2512  0.1338  0.0544]
 [-0.6193  0.621   0.1807 -0.0734]
 [ 0.1809  0.0467 -0.268   0.1867]]


In [128]:
print('completeness_score = ' + str(completeness_score(label,c_pca)))
print('homogeneity_score = '+str(homogeneity_score(label,c_pca)))

completeness_score = 0.5988797141417533
homogeneity_score = 0.597586193178413


In [ ]:
'''
e.
The result of clustering without using pca is better.

clustering:
    completeness_score = 0.6131870124853009
    homogeneity_score = 0.6115021163370862
clustering using 4 components:
    completeness_score = 0.5988797141417533
    homogeneity_score = 0.597586193178413
'''
